Importing Libraries

In [12]:
import pandas as pd
import re
import numpy as np
from nltk.tokenize import TweetTokenizer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

Reading Training Dataset

In [13]:
trainData = pd.read_csv("TrainData.csv","_")
trainData

Index                                            Comment Polarity
0      0             time to eat with my best buddy! #lunch    Happy
1      1  @user @user if they want reflection money. #ksleg    Happy
2      2  ---Good job but I’ will expect a lot more in f...    Happy
3      3  totally dissatisfied with the service###%%@@ n...      Sad
4      4                                 loved my work!!!!!    Happy
5      5        Worst customer care service......@@$$$angry      Sad
6      6                           Brilliant effort guys!!!    Happy
7      7  @user @user you point one finger @user million...      Sad
8      8  words r free, it's how u use that can cost you...    Happy
9      9  you might be a libtard if... #libtard #sjw #li...      Sad

Reading Test Dataset

In [14]:
testData = pd.read_csv("TestData.csv","_")
testData

Index                                            Comment Polarity
0      0  @use the pic says otherwise for young girls co...      Sad
1      1    #good night! ?? #faith ever #vaitacacommafiasdv    Happy
2      2  @user when you're blocked by a troll because y...      Sad
3      3                               dinner with sister!!    Happy
4      4   who else is planning on watching @user tomorrow?    happy

Combining Both Train and Test Datasets

In [15]:
data = trainData.append(testData,ignore_index=True,sort=True)
data

Comment  Index Polarity
0              time to eat with my best buddy! #lunch      0    Happy
1   @user @user if they want reflection money. #ksleg      1    Happy
2   ---Good job but I’ will expect a lot more in f...      2    Happy
3   totally dissatisfied with the service###%%@@ n...      3      Sad
4                                  loved my work!!!!!      4    Happy
5         Worst customer care service......@@$$$angry      5      Sad
6                            Brilliant effort guys!!!      6    Happy
7   @user @user you point one finger @user million...      7      Sad
8   words r free, it's how u use that can cost you...      8    Happy
9   you might be a libtard if... #libtard #sjw #li...      9      Sad
10  @use the pic says otherwise for young girls co...      0      Sad
11    #good night! ?? #faith ever #vaitacacommafiasdv      1    Happy
12  @user when you're blocked by a troll because y...      2      Sad
13                               dinner with sister!!      3    Happy
14   who else is planning on watching @user tomorrow?      4    happy

In [ ]:
Removing Handles @user in the data

In [17]:
def remove_pattern(text,pattern):
    
    # re.findall() finds the pattern i.e @user and puts it in a list for further task
    r = re.findall(pattern,text)
    
    # re.sub() removes @user from the sentences in the dataset
    for i in r:
        text = re.sub(i,"",text)
    
    return text

data['Processed_Comment'] = np.vectorize(remove_pattern)(data['Comment'], "@[\w]*")
data

Comment  Index Polarity  \
0              time to eat with my best buddy! #lunch      0    Happy   
1   @user @user if they want reflection money. #ksleg      1    Happy   
2   ---Good job but I’ will expect a lot more in f...      2    Happy   
3   totally dissatisfied with the service###%%@@ n...      3      Sad   
4                                  loved my work!!!!!      4    Happy   
5         Worst customer care service......@@$$$angry      5      Sad   
6                            Brilliant effort guys!!!      6    Happy   
7   @user @user you point one finger @user million...      7      Sad   
8   words r free, it's how u use that can cost you...      8    Happy   
9   you might be a libtard if... #libtard #sjw #li...      9      Sad   
10  @use the pic says otherwise for young girls co...      0      Sad   
11    #good night! ?? #faith ever #vaitacacommafiasdv      1    Happy   
12  @user when you're blocked by a troll because y...      2      Sad   
13                               dinner with sister!!      3    Happy   
14   who else is planning on watching @user tomorrow?      4    happy   

                                    Processed_Comment  
0              time to eat with my best buddy! #lunch  
1               if they want reflection money. #ksleg  
2   ---Good job but I’ will expect a lot more in f...  
3   totally dissatisfied with the service###%% nev...  
4                                  loved my work!!!!!  
5           Worst customer care service......$$$angry  
6                            Brilliant effort guys!!!  
7     you point one finger  millions are pointed r...  
8   words r free, it's how u use that can cost you...  
9   you might be a libtard if... #libtard #sjw #li...  
10   the pic says otherwise for young girls confin...  
11    #good night! ?? #faith ever #vaitacacommafiasdv  
12   when you're blocked by a troll because you pr...  
13                               dinner with sister!!  
14        who else is planning on watching  tomorrow?

In [ ]:
Removing Punctuations, Numbers, and Special Characters


In [23]:
data['Processed_Comment'] = data['Processed_Comment'].str.replace("[^a-zA-Z#]", " ")
data


Comment  Index Polarity  \
0              time to eat with my best buddy! #lunch      0    Happy   
1   @user @user if they want reflection money. #ksleg      1    Happy   
2   ---Good job but I’ will expect a lot more in f...      2    Happy   
3   totally dissatisfied with the service###%%@@ n...      3      Sad   
4                                  loved my work!!!!!      4    Happy   
5         Worst customer care service......@@$$$angry      5      Sad   
6                            Brilliant effort guys!!!      6    Happy   
7   @user @user you point one finger @user million...      7      Sad   
8   words r free, it's how u use that can cost you...      8    Happy   
9   you might be a libtard if... #libtard #sjw #li...      9      Sad   
10  @use the pic says otherwise for young girls co...      0      Sad   
11    #good night! ?? #faith ever #vaitacacommafiasdv      1    Happy   
12  @user when you're blocked by a troll because y...      2      Sad   
13                               dinner with sister!!      3    Happy   
14   who else is planning on watching @user tomorrow?      4    happy   

                                    Processed_Comment  
0                         time with best buddy #lunch  
1                   they want reflection money #ksleg  
2                   Good will expect more future ####  
3   totally dissatisfied with service### never use...  
4                                          loved work  
5                   Worst customer care service angry  
6                               Brilliant effort guys  
7   point finger millions pointed right back #jewi...  
8   words free that cost #verbal #abuse #love #adu...  
9      might libtard #libtard #sjw #liberal #politics  
10  says otherwise young girls confined that kitch...  
11        #good night #faith ever #vaitacacommafiasdv  
12  when blocked troll because promise #blacklives...  
13                                 dinner with sister  
14                    else planning watching tomorrow

Removing Short Words


In [25]:
data['Processed_Comment'] = data['Processed_Comment'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
data


Comment  Index Polarity  \
0              time to eat with my best buddy! #lunch      0    Happy   
1   @user @user if they want reflection money. #ksleg      1    Happy   
2   ---Good job but I’ will expect a lot more in f...      2    Happy   
3   totally dissatisfied with the service###%%@@ n...      3      Sad   
4                                  loved my work!!!!!      4    Happy   
5         Worst customer care service......@@$$$angry      5      Sad   
6                            Brilliant effort guys!!!      6    Happy   
7   @user @user you point one finger @user million...      7      Sad   
8   words r free, it's how u use that can cost you...      8    Happy   
9   you might be a libtard if... #libtard #sjw #li...      9      Sad   
10  @use the pic says otherwise for young girls co...      0      Sad   
11    #good night! ?? #faith ever #vaitacacommafiasdv      1    Happy   
12  @user when you're blocked by a troll because y...      2      Sad   
13                               dinner with sister!!      3    Happy   
14   who else is planning on watching @user tomorrow?      4    happy   

                                    Processed_Comment  
0                         time with best buddy #lunch  
1                   they want reflection money #ksleg  
2                   Good will expect more future ####  
3   totally dissatisfied with service### never use...  
4                                          loved work  
5                   Worst customer care service angry  
6                               Brilliant effort guys  
7   point finger millions pointed right back #jewi...  
8   words free that cost #verbal #abuse #love #adu...  
9      might libtard #libtard #sjw #liberal #politics  
10  says otherwise young girls confined that kitch...  
11        #good night #faith ever #vaitacacommafiasdv  
12  when blocked troll because promise #blacklives...  
13                                 dinner with sister  
14                    else planning watching tomorrow

In [ ]:
Hash # not removing in the data

In [32]:
Tokenizer = TweetTokenizer()
tList = list()

for i in range(0,5):
    tList.append(Tokenizer.tokenize(dataset.iloc[i,1]))
    
tList


[['@use',
  'the',
  'pic',
  'says',
  'otherwise',
  'for',
  'young',
  'girls',
  'confined',
  'in',
  'that',
  'kitchen',
  '.',
  'you',
  'are',
  'void',
  'of',
  'meaning',
  ',',
  'beyond',
  'cheap',
  'publicity',
  '#topoli'],
 ['#good', 'night', '!', '?', '?', '#faith', 'ever', '#vaitacacommafiasdv'],
 ['@user',
  'when',
  "you're",
  'blocked',
  'by',
  'a',
  'troll',
  'because',
  'you',
  'promise',
  'to',
  '#blacklivesmatter',
  '&',
  'let',
  'his',
  'nonsensical',
  'rants'],
 ['dinner', 'with', 'sister', '!', '!'],
 ['who', 'else', 'is', 'planning', 'on', 'watching', '@user', 'tomorrow', '?']]

In [17]:
labelEncoder = LabelEncoder();
dataset["PolarityEncode"] = labelEncoder.fit_transform(dataset["Polarity"])
dataset

Index                                            Comment Polarity  \
0      0  @use the pic says otherwise for young girls co...      Sad   
1      1    #good night! ?? #faith ever #vaitacacommafiasdv    Happy   
2      2  @user when you're blocked by a troll because y...      Sad   
3      3                               dinner with sister!!    Happy   
4      4   who else is planning on watching @user tomorrow?    happy   

   PolarityEncode  
0               1  
1               0  
2               1  
3               0  
4               2

In [34]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(tList[0])
(vectorizer.get_feature_names())
print(X.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 

In [35]:
words = []
for i in tList:
    for j in i:
        if j not in words:
            words.append(j)
            
words

['@use',
 'the',
 'pic',
 'says',
 'otherwise',
 'for',
 'young',
 'girls',
 'confined',
 'in',
 'that',
 'kitchen',
 '.',
 'you',
 'are',
 'void',
 'of',
 'meaning',
 ',',
 'beyond',
 'cheap',
 'publicity',
 '#topoli',
 '#good',
 'night',
 '!',
 '?',
 '#faith',
 'ever',
 '#vaitacacommafiasdv',
 '@user',
 'when',
 "you're",
 'blocked',
 'by',
 'a',
 'troll',
 'because',
 'promise',
 'to',
 '#blacklivesmatter',
 '&',
 'let',
 'his',
 'nonsensical',
 'rants',
 'dinner',
 'with',
 'sister',
 'who',
 'else',
 'is',
 'planning',
 'on',
 'watching',
 'tomorrow']